./compile.sh run ./D4J/projects/TSQ_project/TSQ_1
./compile.sh run ./D4J/projects/TSQ_project/TSQ_2
./compile.sh run ./D4J/projects/TSQ_project/TSQ_3
./compile.sh run ./D4J/projects/TSQ_project/TSQ_4
./compile.sh run ./D4J/projects/TSQ_project/TSQ_5
./compile.sh run ./D4J/projects/TSQ_project/TSQ_6
./compile.sh run ./D4J/projects/TSQ_project/TSQ_7
./compile.sh run ./D4J/projects/TSQ_project/TSQ_8
./compile.sh run ./D4J/projects/TSQ_project/TSQ_9
./compile.sh run ./D4J/projects/TSQ_project/TSQ_10
./compile.sh run ./D4J/projects/TSQ_project/TSQ_11
./compile.sh run ./D4J/projects/TSQ_project/TSQ_12
./compile.sh run ./D4J/projects/TSQ_project/TSQ_13
./compile.sh run ./D4J/projects/TSQ_project/TSQ_14
./compile.sh run ./D4J/projects/TSQ_project/TSQ_15
./compile.sh run ./D4J/projects/TSQ_project/TSQ_16
./compile.sh run ./D4J/projects/TSQ_project/TSQ_17
./compile.sh run ./D4J/projects/TSQ_project/TSQ_18
./compile.sh run ./D4J/projects/TSQ_project/TSQ_19
./compile.sh run ./D4J/projects/TSQ_project/TSQ_20
./compile.sh run ./D4J/projects/TSQ_project/TSQ_21
./compile.sh run ./D4J/projects/TSQ_project/TSQ_22
./compile.sh run ./D4J/projects/TSQ_project/TSQ_23
./compile.sh run ./D4J/projects/TSQ_project/TSQ_24
./compile.sh run ./D4J/projects/TSQ_project/TSQ_25
./compile.sh run ./D4J/projects/TSQ_project/TSQ_26
./compile.sh run ./D4J/projects/TSQ_project/TSQ_27
./compile.sh run ./D4J/projects/TSQ_project/TSQ_28
./compile.sh run ./D4J/projects/TSQ_project/TSQ_29
./compile.sh run ./D4J/projects/TSQ_project/TSQ_30
./compile.sh run ./D4J/projects/TSQ_project/TSQ_31
./compile.sh run ./D4J/projects/TSQ_project/TSQ_32
./compile.sh run ./D4J/projects/TSQ_project/TSQ_33
./compile.sh run ./D4J/projects/TSQ_project/TSQ_34
./compile.sh run ./D4J/projects/TSQ_project/TSQ_35
./compile.sh run ./D4J/projects/TSQ_project/TSQ_36
./compile.sh run ./D4J/projects/TSQ_project/TSQ_37
./compile.sh run ./D4J/projects/TSQ_project/TSQ_38
./compile.sh run ./D4J/projects/TSQ_project/TSQ_39
./compile.sh run ./D4J/projects/TSQ_project/TSQ_40