language: java

jdk:
  - oraclejdk8

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "PonNNNNiIRXghjef4hsEfIz7LGYzDaET8n4nQHou0+FI2UGrjii56MQwdkHhekipzD+XOXEo46Tw1z588mmsxqe3vTQY2q0hrR2RGXqc2vXCv4FlxQzrtpbeW1chbawCI9tOS4WT92uh/ovoXvIo3WrgG6sJAn//NPPbEwVutN0="
    - secure: "hi1G/aAjxr8nim+rHTPMjR2YfX76SbnfRi28SF+TmGl1wAPxGu06dJfNq8zoqMGY0nCQWkHLNd+YOXZPf7HQt5DCcIhiiisy3Tc13vAtXjbDuYYPKbk/bh+fgTYI5T6XMHUc9DzYtKAtNTUNxZIhhPq2DhWocrMXwt47cg76tyY="

branches:
  except:
    - gh-pages

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.m2
